version: '3.8'

services:
  # Distroless image - absolute minimal
  app-distroless:
    build:
      context: .
      dockerfile: Dockerfile.distroless
    ports:
      - "3001:3000"
    read_only: true
    tmpfs:
      - /tmp:size=10M
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL

  # Alpine hardened image
  app-alpine:
    build:
      context: .
      dockerfile: Dockerfile.alpine
    ports:
      - "3002:3000"
    read_only: true
    tmpfs:
      - /tmp:size=10M
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
